Refactor
petronny/djangorm pull request #1
Opened 2019-06-01 09:13 UTC by laobingm

- 通过创建类来分离初始化和配置
- 通过传参来导入配置

2019-06-03 08:54 UTC, petronny requested changes

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +        self.settings_configure()
多次调用migrate不能多次配置设置，需要有一个变量存储当前示例是否已经配置过

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +    def settings_configure(self):
叫configure就行

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +        conf = {
conf -> configuration

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +        self.settings_configure()
`self.__configured__`

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +    def __init__(self, module_name, default_database={}):
结构体传参默认传None，另外这个不叫default_database，这个不是缺省的。

缺省的default_database配置（sqlite的）应该存在类级别，如果这里没有传参那么应该调用。

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +    orm = DjangORM(module_name=module_name, default_database=database)
orm -> test_db

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +    module_name = 'db'
db -> test

2019-06-03 08:54 UTC, petronny commented on djangorm.py
> +    module_name = 'db'
大家有数据库变量叫db的习惯，别重了

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +        self.settings_configure()
已完成

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +    def settings_configure(self):
已完成

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +        conf = {
已完成

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +    def __init__(self, module_name, default_database={}):
已完成

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +    orm = DjangORM(module_name=module_name, default_database=database)
已完成

2019-06-04 03:00 UTC, laobingm commented on djangorm.py
> +    module_name = 'db'
已完成

2019-06-04 05:22 UTC, petronny requested changes

2019-06-04 05:22 UTC, petronny commented on README.md
> +# demo.py
这行去掉，这个已经不是demo.py的内容了

2019-06-04 05:22 UTC, petronny commented on djangorm.py
> +class DefaultDatabase(dict):
这个不用建类，写成一个dict存`DjangORM.__default_databse__`就行

2019-06-04 05:22 UTC, petronny commented on README.md
> +# test/models.py
test改成`[your_module_name]`可能比较好。这个readme不用太拘泥于现有的demo，说清楚这应该是什么是最好的

2019-06-04 05:22 UTC, petronny commented on README.md
> +test_db.migrate()
就都db吧，也是不用太拘泥于现有的demo

2019-06-04 05:22 UTC, petronny commented on README.md
> +# demo.py
这行删掉吧，已经和demo.py不一致了

2019-06-04 06:57 UTC, laobingm commented
完成

2019-06-04 07:17 UTC, petronny requested changes

2019-06-04 07:17 UTC, petronny commented on README.md
> +* Configure database (MySQL)
改成跟SQLite那句一样，要use都use，要configure就都configure

2019-06-04 07:17 UTC, petronny commented on README.md
> +from test.models import *
这块也改成`[your_module_name]`和db

2019-06-04 07:17 UTC, petronny commented on README.md
> +* If you want to rename the `[your_module_name]` folder, please also change the parameter of `module_name` when used.
这句感觉可以删了

2019-06-04 07:17 UTC, petronny commented on djangorm.py
> +if __name__ == '__main__':
这个main有存在意义么？是不是用demo.py就可以了？

2019-06-04 07:44 UTC, laobingm commented
完成

2019-06-04 07:56 UTC, petronny requested changes

2019-06-04 07:56 UTC, petronny commented on README.md
>  # demo.py
这个demo.py也去掉吧

2019-06-04 07:56 UTC, petronny commented on README.md
> +
多余空行？

2019-06-04 07:56 UTC, petronny commented on djangorm.py
> +        self.__default_databse__ = {
这个不需要每个实例存一个，存到类级别

2019-06-04 07:56 UTC, petronny commented on djangorm.py
> +                'default': self.database if self.database else self.__default_databse__
这个判断挪到`__init__`中

2019-06-04 08:08 UTC, laobingm commented on README.md
> +
不是多余的，和其他代码块保持队形。

2019-06-04 08:23 UTC, laobingm commented
完成

2019-06-04 08:37 UTC, petronny requested changes

2019-06-04 08:37 UTC, petronny commented on djangorm.py
> +            database = __default_databse__
这过得去么？感觉应该写成`DjangORM.__default_databse__`

2019-06-04 08:37 UTC, petronny commented on djangorm.py
> +        if database is not None and not isinstance(database, dict):
这的is None判断多余了

2019-06-04 08:37 UTC, petronny commented on djangorm.py
> +        if not self.__configured__:
虽然这里保证了migrate前必定configure，但是所有的demo应该都手动调用一遍。

2019-06-04 08:37 UTC, petronny commented on djangorm.py
> +        if not self.__configured__:
因为migrate不一定是必需的。会有人只做手动migrate

2019-06-04 09:31 UTC, laobingm commented
完成

2019-06-04 09:39 UTC, petronny requested changes

2019-06-04 09:39 UTC, petronny commented on demo.py
> +from test.models import *
这行前空一下？

2019-06-04 09:39 UTC, petronny commented on djangorm.py
> +    def migrate(self):
这要么保证configure过，要么加上没configure过的报错

2019-06-04 12:17 UTC, laobingm commented
完成

2019-06-04 15:35 UTC, petronny approved these changes

2019-06-04 15:37 UTC, petronny commented
commit数量适当删少，commit message请说明再具体一点点。

2019-06-05 03:24 UTC, laobingm commented
> commit数量适当删少，commit message请说明再具体一点点。

完成

2019-06-07 07:11 UTC, merged